name: dotNet Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # every hour at minute 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore Dependencies
        run: dotnet Restore
        working-directory: ./m4gh4w

      - name: Build Project
        run: dotnet build --no-restore --configuration Release
        working-directory: ./m4gh4w

      - name: Run TEsts
        run: dotnet test --no-build --verbosity normal
        working-directory: ./m4gh4w