name: dotNet Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # every hour at minute 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore Dependencies
        uses: dotnet Restore

      - name: Build Project
        uses: dotnet build --no-restore --configuration Release

      - name: Run TEsts
        uses: dotnet test --no-build --verbosity normal